action_executor:
  type: base_policy_runner
  policy_shm_name: policy_actions
  robot_control_shms:
    - shm: RizonRobot_1_control
      shape: [8]
      dtype: float64
  execution_fps: 10.0
  chunk_length: ${policy.chunk_length}
  chunk_manager: 
    type: nodelay_manager
    dt: 0.1
      
