defaults:
  - devices: hik_collect
  - device_manager: hik_collect
  - consumer: default
  - action_executor: default
  - runtime: default
  - _self_

# Camera configuration - modify these to change camera IDs
camera:
  left_id: 0
  right_id: 1

global_settings:
  log_level: "INFO"
  restart_on_failure: true
  max_restart_attempts: 3
  restart_delay: 2.0
  device_init_delay: 8.0

hydra:
  run:
    dir: .
  output_subdir: null
